MFIX-Exa: FixInputs Class Reference
FixInputs Class Reference
Public Member Functions
FixInputs (int is_IOProc)
template<class T >
void fix (ParmParse &ppA, ParmParse &ppB, const char *input_string, bool deprecated=false)
template<class T >
void fix_arr (ParmParse &ppA, ParmParse &ppB, const char *input_string, bool deprecated=false)
Constructor & Destructor Documentation
FixInputs()
FixInputs::FixInputs (int is_IOProc) inline
Member Function Documentation
fix()
template<class T > void FixInputs::fix (ParmParse & ppA, ParmParse & ppB, const char * input_string, bool deprecated = false) inline
Referenced by fix_par(), and fix_par_for_backward_compatibility().
fix_arr()
template<class T > void FixInputs::fix_arr (ParmParse & ppA, ParmParse & ppB, const char * input_string, bool deprecated = false) inline
Referenced by fix_par_for_backward_compatibility().
The documentation for this class was generated from the following file:
mfix/src/main.cpp