MFIX-Exa: EulerianMonitor::BaseMonitor::isCovered Class Reference
EulerianMonitor::BaseMonitor::isCovered Class Reference
#include <mfix_monitors.H>
Public Member Functions
AMREX_GPU_HOST_DEVICE isCovered ()
AMREX_GPU_HOST_DEVICE isCovered (const int ix_type, const int direction=-1)
AMREX_GPU_HOST_DEVICE void set_direction (const int direction)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE int operator() (const amrex::Array4< amrex::EBCellFlag const > &flags_arr, const amrex::IntVect &ijk) const
Constructor & Destructor Documentation
isCovered() [1/2]
AMREX_GPU_HOST_DEVICE EulerianMonitor::BaseMonitor::isCovered::isCovered () inline
isCovered() [2/2]
AMREX_GPU_HOST_DEVICE EulerianMonitor::BaseMonitor::isCovered::isCovered (const int ix_type, const int direction = -1) inline
Member Function Documentation
operator()()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE int EulerianMonitor::BaseMonitor::isCovered::operator() (const amrex::Array4< amrex::EBCellFlag const > & flags_arr, const amrex::IntVect & ijk) const inline
set_direction()
AMREX_GPU_HOST_DEVICE void EulerianMonitor::BaseMonitor::isCovered::set_direction (const int direction) inline
Referenced by EulerianMonitor::AreaMonitor::initialize(), EulerianMonitor::AreaRegion::initialize(), and EulerianMonitor::SurfaceIntegral::initialize().
The documentation for this class was generated from the following file:
mfix/src/io/mfix_monitors.H