MFIX-Exa: mfix/src/des/mfix_des_K.H File Reference
mfix_des_K.H File Reference
#include <AMReX_REAL.H>
#include <AMReX_Gpu.H>
#include <AMReX_RealVect.H>
#include <AMReX_Array.H>
Functions
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void cross_product (const amrex::RealVect &a, const amrex::RealVect &b, amrex::RealVect &c)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real dot_product (const amrex::RealVect &a, const amrex::RealVect &b)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real interp_level_set (const amrex::RealVect &pos, const int n_refine, amrex::Array4< amrex::Real const > const &phi, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const &plo, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const &dxi)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void level_set_normal (const amrex::RealVect &pos, const int n_refine, amrex::RealVect &normal, amrex::Array4< amrex::Real const > const &phi, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const &plo, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const &dxi)
Function Documentation
cross_product()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void cross_product (const amrex::RealVect & a, const amrex::RealVect & b, amrex::RealVect & c)
dot_product()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real dot_product (const amrex::RealVect & a, const amrex::RealVect & b)
Referenced by level_set_normal(), and mfix::mfix_calc_transfer_coeffs().
interp_level_set()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real interp_level_set (const amrex::RealVect & pos, const int n_refine, amrex::Array4< amrex::Real const > const & phi, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const & plo, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const & dxi)
Referenced by MFIXParticleContainer::RemoveOutOfRange().
level_set_normal()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void level_set_normal (const amrex::RealVect & pos, const int n_refine, amrex::RealVect & normal, amrex::Array4< amrex::Real const > const & phi, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const & plo, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const & dxi)
References dot_product().