name: Build-and-Deploy

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Build Sphinx manual HTML target
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:

      - name: Install dependencies
        run: pip install sphinx sphinx-rtd-theme

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build MFiX-Exa HTML manual
        run: make -C docs
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
